name: aluupvc_trial
description: Pro trial (v0.3) for Aluminum/UPVC deductions with scan + projects + stock cutting.
publish_to: 'none'
version: 0.3.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  share_plus: ^10.0.2
  image_picker: ^1.0.8
  google_mlkit_text_recognition: ^0.13.0
  file_picker: ^8.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/rules_default.json
